# Default initial positions for Melon's ros2_control fake system

initial_positions:
  fr3_finger_joint1: 0
  fr3_joint1: 0
  fr3_joint2: 0
  fr3_joint3: 0
  fr3_joint4: 0
  fr3_joint5: 0
  fr3_joint6: 0
  fr3_joint7: 0
  left_wheel_joint: 0
  right_wheel_joint: 0
  virtual_joint: 0